name: app_flutter
description: An app built using Flutter for web

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  after_init: ^0.1.2
  firebase: ^5.0.4
  flutter_html: ^0.11.0
  provider: ^4.0.5
  rxdart: ^0.22.2
  universal_html: ^1.1.4
  fluro: ^1.6.3
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  dfunc: ^0.3.4
  equatable: ^1.1.1
  core:
    path: ../core/

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  dfunc_builder: ^0.0.3


flutter:
  assets:
    - assets/
