linter:
  rules:
    # ERRORS
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - empty_statements
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    # STYLE
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_implementing_value_types
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_renaming_method_parameters
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - avoid_returning_null
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_types
    - cascade_invocations
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - file_names
    - flutter_style_todos
    - implementation_imports
    - join_return_with_assignment
    - library_names
    - library_prefixes
    - lines_longer_than_80_chars
    - non_constant_identifier_names
    - null_closures
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - recursive_getters
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_to_and_as_if_applicable
    - void_checks
    # PUB RULES
    - package_names
    - sort_pub_dependencies

analyzer:
  errors:
    must_call_super: error
    avoid_empty_else: warning
    avoid_relative_lib_imports: error
    avoid_returning_null_for_future: error
    avoid_types_as_parameter_names: error
    cancel_subscriptions: warning
    close_sinks: warning
    empty_statements: warning
    hash_and_equals: warning
    iterable_contains_unrelated_type: error
    list_remove_unrelated_type: error
    literal_only_boolean_expressions: warning
    no_adjacent_strings_in_list: warning
    no_duplicate_case_values: error
    prefer_void_to_null: error
    test_types_in_equals: error
    throw_in_finally: error
    unnecessary_statements: warning
    unrelated_type_equality_checks: error
    always_declare_return_types: warning
    always_require_non_null_named_parameters: warning
    annotate_overrides: warning
    avoid_bool_literals_in_conditional_expressions: warning
    avoid_catches_without_on_clauses: info
    avoid_catching_errors: warning
    avoid_classes_with_only_static_members: warning
    avoid_implementing_value_types: error
    avoid_null_checks_in_equality_operators: warning
    avoid_positional_boolean_parameters: info
    avoid_private_typedef_functions: info
    avoid_renaming_method_parameters: error
    avoid_init_to_null: warning
    avoid_return_types_on_setters: error
    avoid_returning_null: warning
    avoid_returning_null_for_void: warning
    avoid_returning_this: warning
    avoid_shadowing_type_parameters: error
    avoid_single_cascade_in_expression_statements: warning
    avoid_unused_constructor_parameters: warning
    avoid_void_async: warning
    await_only_futures: error
    camel_case_types: error
    cascade_invocations: warning
    constant_identifier_names: error
    curly_braces_in_flow_control_structures: warning
    directives_ordering: error
    empty_catches: warning
    empty_constructor_bodies: warning
    file_names: error
    flutter_style_todos: warning
    implementation_imports: error
    join_return_with_assignment: warning
    library_names: error
    library_prefixes: error
    lines_longer_than_80_chars: warning
    non_constant_identifier_names: error
    null_closures: error
    one_member_abstracts: info
    only_throw_errors: error
    overridden_fields: error
    package_api_docs: info
    package_prefixed_library_names: error
    parameter_assignments: error
    prefer_adjacent_string_concatenation: warning
    prefer_asserts_in_initializer_lists: warning
    prefer_asserts_with_message: info
    prefer_collection_literals: warning
    prefer_conditional_assignment: warning
    prefer_const_constructors: warning
    prefer_const_constructors_in_immutables: warning
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_constructors_over_static_methods: warning
    prefer_contains: warning
    prefer_equal_for_default_values: warning
    prefer_expression_function_bodies: warning
    prefer_final_fields: warning
    prefer_final_in_for_each: warning
    prefer_final_locals: warning
    prefer_foreach: warning
    prefer_generic_function_type_aliases: warning
    prefer_if_elements_to_conditional_expressions: warning
    prefer_if_null_operators: warning
    prefer_initializing_formals: warning
    prefer_inlined_adds: warning
    prefer_int_literals: warning
    prefer_interpolation_to_compose_strings: warning
    prefer_is_empty: warning
    prefer_is_not_empty: warning
    prefer_iterable_whereType: warning
    prefer_mixin: warning
    prefer_null_aware_operators: warning
    prefer_single_quotes: warning
    prefer_spread_collections: warning
    prefer_typing_uninitialized_variables: warning
    recursive_getters: error
    slash_for_doc_comments: warning
    sort_child_properties_last: warning
    sort_constructors_first: warning
    sort_unnamed_constructors_first: warning
    type_annotate_public_apis: warning
    type_init_formals: warning
    unawaited_futures: warning
    unnecessary_await_in_return: warning
    unnecessary_brace_in_string_interps: warning
    unnecessary_const: warning
    unnecessary_getters_setters: warning
    unnecessary_lambdas: warning
    unnecessary_new: warning
    unnecessary_null_aware_assignments: warning
    unnecessary_null_in_if_null_operators: warning
    unnecessary_overrides: warning
    unnecessary_parenthesis: info
    unnecessary_this: info
    use_full_hex_values_for_flutter_colors: warning
    use_function_type_syntax_for_parameters: warning
    use_rethrow_when_possible: warning
    use_setters_to_change_properties: warning
    use_to_and_as_if_applicable: warning
    void_checks: error
    package_names: error
    sort_pub_dependencies: error
  exclude:
    - '**/*.g.dart'
    - 'flutter/**'
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
